# Generated by Django 5.0 on 2024-02-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='precio',
            new_name='price',
        ),
    ]
