# Generated by Django 5.0 on 2024-02-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_precio_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('direccion', models.CharField(max_length=128)),
                ('ciudad', models.CharField(max_length=128)),
                ('codigo_postal', models.CharField(max_length=128)),
                ('provincia', models.CharField(max_length=128)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
